# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EscapePass' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Auth'
pod 'FBSDKLoginKit'
pod 'Firebase/Database'
pod 'Firebase/Storage'
  # Pods for EscapePass

  target 'EscapePassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EscapePassUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
